version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
  login-service:
    build:
      context: ./services/login-service
    container_name: login-service
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:rootPassword@mongo:27017/auth?authSource=admin
      - JWT_SECRET=secretKey
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  vue-app:
    build:
      context: ./services/vue-app
    container_name: vue-app
    environment:
      - VITE_LOGIN_SERVICE=http://localhost:3000/api/auth
    ports:
      - '8080:8080'
