apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - image: selvaprasath27/login-service
          name: login-service
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: MONGO_URI
              value: 'mongodb://root:rootPassword@mongo-service:27017/auth?authSource=admin'
            - name: JWT_SECRET
              value: 'secretKey'
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: LoadBalancer
  selector:
    app: login-service
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootPassword

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - image: selvaprasath27/vue-app:latest
          name: vue-app
          ports:
            - containerPort: 8080
          env:
            - name: VITE_LOGIN_SERVICE
              value: 'http://localhost:3000/api/auth'

---
apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  type: LoadBalancer
  selector:
    app: vue-app
  ports:
    - port: 8080
      targetPort: 8080
