apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 2
  selector:
   matchLabels:
    app: vue-app
  template:
   metadata:
    labels:
     app: vue-app
   spec:
    containers:
     - image: selvaprasath27/vue-app:latest
       name: vue-app
       ports:
        - containerPort: 8080
       env:
        - name: VITE_LOGIN_SERVICE
          value: "http://localhost:3000/api/auth"
